DATA_DIR = "data"

FILE_ROOMS    = "rooms.csv"
FILE_SLOTS    = "slots.csv"
FILE_TEACHERS = "teacher_lookup.csv"
FILE_DEMANDS  = "course_demands_transformed_fullname.csv"

WILDCARD_GROUPS: set[str] = {"ĐHKHTN", "DHKHTN","ĐHGD","DHGD","HỌC LẠI", "HOC LAI","ĐẠI CƯƠNG", "DAI CUONG", "KHTN", "CNKHTN"}

# 1. DATA SETTINGS

USE_REAL_DATA_SLOTS = True
TOTAL_TIMESLOTS_EXPECTED = 72   


# 2. GENETIC ALGORITHM (GLOBAL SEARCH)

POP_SIZE       = 100   
GENERATIONS    = 800   
CROSSOVER_PROB = 0.9    
MUTATION_PROB  = 0.9    
TOURNAMENT_K   = 10     
ELITISM_COUNT  = 2    


MUTATION_DEMAND_RATE = 0.02


MUTATION_CONFLICT_BOOST = 1.5


CHILD_HARD_WORSE_TOL = 3
RESTART_THRESHOLD = 80
RESTART_KEEP_RATIO = 0.03

USE_GREEDY_SEED = True
GREEDY_RATIO    = 0.1

# 3. FITNESS FUNCTION

# fitness(S) = -(ALPHA * hard_penalty + BETA * soft_penalty)
ALPHA = 1000
BETA  = 1

USE_DYNAMIC_ALPHA = True

WEIGHT_PREFER_SHIFT     = 2.0   
WEIGHT_SPREAD_DAYS      = 1.5   
WEIGHT_CONSECUTIVE      = 1.0   
WEIGHT_GAP              = 0.5   

# 4. LOCAL SEARCH (TABU SEARCH)

USE_TABU = True

LOCAL_SEARCH_ITERATIONS = 300 
NEIGHBOR_SAMPLE_SIZE    = 80 
TABU_TENURE             = 16

FOCUS_HARD_FIRST = True

# 5. BACKTRACKING REPAIR

MAX_REPAIR_STEPS = 0

MAX_REPAIR_DEPTH = 180

REPAIR_TIMEOUT_SECONDS = 300

REPAIR_FOCUS_HARD_ONLY = True

REPAIR_EARLY_STOPPING = False
REPAIR_NO_IMPROVE_LIMIT = 400

REPAIR_RANDOM_SEED = 3

REPAIR_MAX_TEACHER_CANDIDATES = 12
REPAIR_MAX_ROOM_CANDIDATES = 16
REPAIR_MAX_SLOTGROUP_CANDIDATES = 80

REPAIR_DYNAMIC_EXPAND_HOPS = 1
REPAIR_DYNAMIC_EXPAND_BUDGET = 120
REPAIR_HARD_FOCUS_CAP = 120

REPAIR_RESAMPLE_ATTEMPTS = 8
REPAIR_STALE_EXPAND_EVERY = 2
REPAIR_STALE_HOPS_STEP = 1
REPAIR_STALE_CAP_STEP = 20
REPAIR_STALE_BUDGET_STEP = 20

# 6. SOFT CONSTRAINT THRESHOLDS

MAX_CONSECUTIVE_SLOTS = 6
MAX_SLOTS_PER_DAY     = 7
MAX_GAP_ALLOWED       = 2

MORNING_PERIODS = [1, 2, 3, 4, 5, 6]
AFTERNOON_PERIODS = [7, 8, 9, 10, 11, 12, 13]

# 7. ROOM SETTINGS

ROOM_TYPE_NORMAL   = 0      # Phong thuong
ROOM_TYPE_COMPUTER = 1      # Phong may / lab

# 8. RANDOM SEED

RANDOM_SEED = 42

# 9. EARLY STOPPING

EARLY_STOPPING   = True
NO_IMPROVE_LIMIT = 200

# 10. TRACKING & DEBUG

VERBOSE            = True
TRACK_HARD_PENALTY = True
TRACK_SOFT_PENALTY = True

SAVE_HISTORY = True
HISTORY_FILE = "fitness_history.json"

PLOT_FITNESS = True

# 11. OUTPUT

SAVE_RESULT = True
OUTPUT_FILE = "final_schedule.json"
